# Generated by Django 6.0.2 on 2026-02-27 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_category', models.CharField(choices=[('Leptop', 'Laptop'), ('Mobile', 'Mobile'), ('Headphones', 'Headphones'), ('Smart Watch', 'Smart Watch')], max_length=100)),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_price', models.PositiveIntegerField()),
                ('Product_desc', models.TextField()),
                ('Product_image', models.ImageField(upload_to='product_images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
