# Generated by Django 6.0.2 on 2026-03-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_price',
            new_name='Product_price',
        ),
    ]
