file=open("Tops1.txt","w")
file.write("This is file management using Python.")
file.close()
print("File written successfully")
print("*****************************************************")

file=open("Tops1.txt","r")
print(file.read())
file.close()
print("*****************************************************")

file=open("Tops1.txt","a")
file.write("\nThis is file now appended.")
file.close()
print("File appended successfully")
print("*****************************************************")

file=open("TOsd2.txt","w+")
file.write("This is w+ Mode in file")
print("current file position : ",file.tell())
file.seek(0)
print("File Data ; ",file.read())
file.close()
print("File written successfully")
print("*****************************************************")
